defaults: &defaults
  nfs: /mapr/qomo.cbb/qomo_<%= Rails.env%>
  admin:
    username: xingjian
    email: qomocloud@big.ac.cn
  tools:
    bundle:
      - https://github.com/qomoteam/kakscalc-qomo.git
  lib:
    streaming: hadoop-streaming-2.7.0-mapr-1506.jar
    common: qomo-common-0.0.1-SNAPSHOT.jar
  hadoop:
    username: qomo
    bin: /opt/mapr/bin/hadoop
    hdfs: /mapr/qomo.cbb
  spark:
    submit: /opt/mapr/spark/spark-1.5.2/bin/spark-submit
    master: spark://host2:7077

  rmq:
    host: h2
    user: qomo
    pass: qomo
    vhost: qomo


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
