defaults: &defaults
  nfs: /mapr/qomo.cbb/qomo_<%= Rails.env%>
  admin:
    username: xingjian
    email: xuxingjian@big.ac.cn
  tools:
    bundle:
      - https://github.com/qomoteam/kakscalc-qomo.git


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
