Tech.create name: 'Unknown'
Tech.create name: 'Single-thread'
Tech.create name: 'Multoprocess'
Tech.create name: 'MPI'
Tech.create name: 'GPU'
Tech.create name: 'R'
Tech.create name: 'Spark'
Tech.create name: 'Hadoop'
